name: Clean Repository
on:
  workflow_dispatch:
    inputs:
      CLEAN_CACHE:
        description: "是否清理 GitHub Actions 缓存"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
          
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete all except .github and README.md
        run: |
          # 列出所有文件/目录（除 .github 和 README.md）
          find . -mindepth 1 -maxdepth 1 \
            ! -name '.github' \
            ! -name 'README.md' \
            ! -name '.git' \
            -exec rm -rf {} +
          
          # 提交更改
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "清理仓库：只保留 .github 和 README.md" || echo "没有变更"
          git push

      - name: Delete branch cache
        if: github.event.inputs.CLEAN_CACHE == 'true'
        uses: snnaplab/delete-branch-cache-action@v1
        with:
          ref: refs/pull/${{ github.event.number }}/merge  # 指定Pull Request的ref
          github-token: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub Token
