name: Clean Repository
on:
  workflow_dispatch:
    inputs:
      CLEAN_CACHE:
        description: "是否清理 GitHub Actions 缓存"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
          
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete all except .github and README.md
        run: |
          # 列出所有文件/目录（除 .github 和 README.md）
          find . -mindepth 1 -maxdepth 1 \
            ! -name '.github' \
            ! -name 'README.md' \
            ! -name '.git' \
            -exec rm -rf {} +
          
          # 提交更改
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "清理仓库：只保留 .github 和 README.md" || echo "没有变更"
          git push


      - name: Clear GitHub Actions cache (if enabled)
        if: github.event.inputs.CLEAN_CACHE == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 设置 GitHub token 进行身份验证
        run: |
          echo "清理 GitHub Actions 缓存..."
          # 删除所有 GitHub Actions 缓存
          gh api -X DELETE /repos/${{ github.repository }}/actions/caches
