name: Package Build

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Changed packages"
        required: false
        default: ""  # 默认值为空
jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 24.10.0
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up packages
        run: |
          # 如果输入了 packages 参数，则使用它；否则，使用默认值
          if [ -z "${{ github.event.inputs.packages }}" ]; then
            echo "No specific packages provided. Using default."
            PACKAGES="filebrowser luci-app-autoreboot luci-app-homeproxy luci-app-nikki luci-app-zerotier miniupnpc zerotier libnatpmp luci-app-filebrowser luci-app-lucky luci-app-openclash luci-theme-argon luci-app-argon-config"
          else
            echo "Using provided packages: ${{ github.event.inputs.packages }}"
            PACKAGES="${{ github.event.inputs.packages }}"
          fi
          echo "PACKAGES=${PACKAGES}" >> $GITHUB_ENV

      - name: Build
        uses: kenzok8/gh-action-sdk@hash
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: filebrowser luci-app-autoreboot luci-app-homeproxy luci-app-nikki luci-app-zerotier miniupnpc zerotier libnatpmp luci-app-filebrowser luci-app-lucky luci-app-openclash luci-theme-argon luci-app-argon-config
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

          
      - name: Upload packages
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.GH_PAT }}
          artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ github.run_number }}-${{ matrix.arch }}


