name: Package Build

on:
  workflow_dispatch:
  push:
    tags:
      - v.**

jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 24.10.0
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build
        uses: kenzok8/gh-action-sdk@hash
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: filebrowser luci-app-autoreboot luci-app-homeproxy luci-app-nikki luci-app-zerotier miniupnpc zerotier libnatpmp luci-app-filebrowser luci-app-lucky luci-app-openclash luci-theme-argon luci-app-argon-config
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Store packages
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

          
      - name: Upload packages
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.GH_PAT }}
          artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ github.run_number }}-${{ matrix.arch }}

      - name: Delete releases tags and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          #设置是否删除 releases 文件（选项：true/false），默认为 false。
          delete_releases: true
          #设置是否删除与 Releases 关联的 tags（选项：true/false），默认为 false。
          delete_tags: true
          #设置是否区分预发行版本（选项：all/true/false）。all表示全部类型，true/false代表仅删除标记为此类型的 releases 文件。默认为 all。
          prerelease_option: all
          #设置保留几个最新的 Releases 版本（整数。如：5），设置为 0 表示全部删除，默认保留 90 个。
          releases_keep_latest: 6
          #设置需要保留的 Releases 的 tags 关键字，多个关键字使用 / 分割（例如：book/tool），默认值 无。
          #releases_keep_keyword: 
          #设置是否删除 workflows 运行记录（选项：true/false），默认为 false。
          delete_workflows: true
          #设置保留几天以内的 workflows 记录（整数。如：30），设置为 0 表示全部删除。默认为 90 天。
          workflows_keep_day: 6
          #设置需要保留的 workflows 运行记录的名称关键字，多个关键字使用 / 分割（例如：book/tool），默认值 无。
          #workflows_keep_keyword:
          #设置是否输出详细的 json 日志（选项：true/false），默认值 false。
          #out_log: 
          #设置执行操作的 <owner>/<repo> ，默认为当前仓库。
          #repo: 
          gh_token: ${{ secrets.GITHUB_TOKEN }}
